# Generated by Django 6.0 on 2026-01-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('card', 'Card')], default='post', max_length=12),
        ),
    ]
