# Generated by Django 6.0 on 2026-01-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_entry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='summary',
        ),
    ]
