# Generated by Django 5.0.4 on 2024-09-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('submissions', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PageStats',
            fields=[
                ('url', models.TextField(primary_key=True, serialize=False)),
                ('views', models.IntegerField(default=1)),
            ],
        ),
    ]
